export const productArray = [
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/blue",
    image: "./images/product-image1.jpg",
    id: "1",
    price: "699",
    alt: "a product image of a women wearing a yellow rain jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/blue",
    image: "./images/product-image8.jpg",
    id: "2",
    price: "599",
    alt: "a product image of man wearing a long dark green rain jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/blue",
    image: "./images/product-image4.jpg",
    id: "3",
    price: "899",
    alt: "a product image from behind of a man wearing a green rain jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/green",
    image: "./images/product-image22.jpg",
    id: "4",
    price: "399",
    alt: "a product image from behind of a man wearing a green rain jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/green",
    image: "./images/product-image6.jpg",
    id: "5",
    price: "699",
    alt: "a product image of a man wear a grey ski jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/green",
    image: "./images/product-image16.jpg",
    id: "6",
    price: "999",
    alt: "a proudct image of a women wearing a blue jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/green",
    image: "./images/product-image15.jpg",
    id: "7",
    price: "799",
    alt: "a proudct image of a women wearing a dark green jacket",
  },
  {
    name: "Rainydays",
    description: "Wind Jackets-Navy/green",
    image: "./images/product-image18.jpg",
    id: "8",
    price: "799",
    alt: "a proudct image of a women wearing a dark red jacket",
  },
];
